eksctl create nodegroup \
  --cluster Pulkit-eks \
  --region ap-south-1 \
  --name node2 \
  --node-type t3.medium \
  --nodes 2 \
  --nodes-min 1 \
  --nodes-max 2 \
  --node-volume-size 20 \
  --ssh-access \
  --ssh-public-key <> \
  --managed \
  --asg-access \
  --external-dns-access \
  --full-ecr-access \
  --appmesh-access \
  --alb-ingress-access \
  --node-private-networking \
  --subnet-ids <>,<> 
